<?php
/**
 * @file
 * Drupal hooks for this module.
 */

define('CES_USER_NEW_EXCHANGE_URL', 'ces_user_new_exchange_url');
define('CES_USER_DOCUMENTATION_URL', 'ces_user_documentation_url');
define('CES_USER_DEVELOPERS_URL', 'ces_user_developers_url');
define('CES_USER_DONATE_URL', 'ces_user_donate_url');
define('CES_USER_TERMS_OF_SERVICE_URL', 'ces_user_terms_of_service_url');
define('CES_USER_ABOUT_URL', 'ces_user_about_url');
define('CES_USER_GOOGLE_MAPS_KEY', 'ces_user_google_maps_key');

define('CES_USER_NEW_EXCHANGE_URL_DEF', 'ces/bank/exchange/new?lang=@langcode');
define('CES_USER_DOCUMENTATION_URL_DEF', 'http://docs.integrales.net');
define('CES_USER_DEVELOPERS_URL_DEF', 'https://www.drupal.org/project/ices');
define('CES_USER_DONATE_URL_DEF', 'https://www.coopfunding.net/campaigns/integralces');
define('CES_USER_TERMS_OF_SERVICE_URL_DEF', '');
define('CES_USER_ABOUT_URL_DEF', '');

/**
 * @defgroup ces_user Ces User
 * @ingroup ices
 * @{
 * Ces User module
 */

/**
 * Special permissions access callback for CES user.
 *
 * True for exhange and user admins.
 */
function ces_user_access($user_edit) {
  global $user;

  if (user_edit_access($user_edit)) {
    return TRUE;
  }

  // Check actual user is admin of actual exchange.
  if (!ces_bank_access('admin', 'exchange', CES_BANK_CURRENT_EXCHANGE)) {
    return FALSE;
  }

  // Check user to edit is not admin of Drupal.
  if (user_access('administer users', $user_edit)) {
    return FALSE;
  }

  // Check user to edit is from actual exchange.
  $bank = new CesBank();
  $accounts = $bank->getUserAccounts($user_edit->uid);
  $exchange = ces_bank_get_current_exchange();
  $current_exchange = $exchange['id'];
  foreach ($accounts as $account) {
    if ($account['exchange'] == $current_exchange) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Implements hook_menu().
 *
 * Access to config/user-interface/ces_user for site config admins.
 */
function ces_user_menu() {
  $menu = array();
  $menu['ces'] = array(
    'title' => 'Welcome to Integral CES',
    'access callback' => TRUE,
    'page callback' => 'ces_user_main_page',
    'type' => MENU_CALLBACK,
  );
  $menu['ces/user/registered/%'] = array(
    'title' => 'Successfuly registered to Integral CES',
    'access callback' => TRUE,
    'page callback' => 'ces_user_registered',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
  );
  $menu['admin/config/user-interface/ces_user'] = array(
    'title' => 'ICES user settings',
    'description' => 'Change global settings related to IntegralCES user module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ces_user_admin'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $menu;
}
/**
 * Implements hook_menu_alter().
 */
function ces_user_menu_alter(&$menu) {
  // Gain control over registration page.
  $menu['user/register']['page arguments'] = array('ces_user_register_form');

  // Admin exchange can edit user profile.
  $menu['user/%user/edit']['access callback'] = 'ces_user_access';

}
/**
 * Returns the full name for given account, or the current one if NULL.
 */
function ces_user_get_name($account = NULL) {
  if ($account == NULL) {
    global $user;
    $account = user_load($user->uid);
  }
  $items = field_get_items('user', $account, 'ces_firstname');
  $userfullname = '';
  if (!empty($items)) {
    $item = reset($items);
    $userfullname = $item['safe_value'] . ' ';
  }
  $items = field_get_items('user', $account, 'ces_surname');
  if (!empty($items)) {
    $item = reset($items);
    $userfullname .= $item['safe_value'];
  }
  if (empty($userfullname)) {
    $userfullname = $account->name;
  }
  return trim($userfullname);
}
/**
 * Returns the address for given account, or the current one if NULL.
 */
function ces_user_get_full_address($account = NULL) {
  if ($account == NULL) {
    global $user;
    $account = user_load($user->uid);
  }
  $items = field_get_items('user', $account, 'ces_address');
  $address = '';
  if (!empty($items)) {
    $item = reset($items);
    $address = $item['value'];
  }
  $items = field_get_items('user', $account, 'ces_postcode');
  if (!empty($items)) {
    $item = reset($items);
    if ($address != '') {
      $address .= ', ';
    }
    $address .= $item['value'];
  }
  $items = field_get_items('user', $account, 'ces_town');
  if (!empty($items)) {
    $item = reset($items);
    if ($address != '') {
      $address .= ', ';
    }
    $address .= $item['value'];
  }
  return $address;
}
/**
 * Returns the main phone number for given account, or the current one if NULL.
 */
function ces_user_get_main_phone($account = NULL) {
  if ($account == NULL) {
    global $user;
    $account = user_load($user->uid);
  }
  $order = array('ces_phonemobile', 'ces_phonework', 'ces_phonehome');
  foreach ($order as $name) {
    $items = field_get_items('user', $account, $name);
    if (!empty($items)) {
      $item = reset($items);
      return $item['safe_value'];
    }
  }
  return '';
}
function _ces_user_register_form_page(&$form_state) {
  if (empty($form_state['page'])) {
    module_load_include('module', 'ces_bank');
    $exchange = ces_bank_get_current_exchange();
    $require_terms = !empty($exchange['data']['require_terms']);

    $form_state['page'] = $require_terms ? 'terms' : 'account';
  }
  return $form_state['page'];
}
/**
 * Tweaked user register form.
 */
function ces_user_register_form($form, &$form_state) {
  $page = _ces_user_register_form_page($form_state);
  if ($page == 'terms') {
    $form = ces_user_terms_form($form, $form_state);
  }
  else if ($page == 'account') {
    $form = user_register_form($form, $form_state);
    $form['actions']['previous'] = array(
      '#type' => 'submit',
      '#value' => t('<< Previous'),
      '#submit' => array('ces_user_register_save_values', 'ces_user_register_form_previous'),
      '#limit_validation_errors' => array(),
    );
  }
  else {
    $form = array();
    $form['actions'] = array(
      '#weight' => 10000,
    );
    $form['actions']['submit'] = array(
      '#prefix' => '<div>',
      '#suffix' => '</div>',
      '#type' => 'submit',
      '#value' => t('Submit registration'),
      '#weight' => 1000,
    );
  }
  $form['actions']['submit']['#submit'] = array('ces_user_register_save_values', 'ces_user_register_submit');
  return $form;
}
function ces_user_terms_form($form, &$form_state) {

  $form = array();
  module_load_include('module', 'ces_bank');
  $exchange = ces_bank_get_current_exchange();
  $form['title'] = array(
    '#prefix' =>'<h3>',
    '#markup' => t('Mebership terms of :exchange', array(':exchange' => $exchange['name'])),
    '#suffix' => '</h3>',
  );
  $form['text'] = array(
    '#prefix' => '<div>',
    '#suffix' => '</div>',
    '#markup' => check_markup($exchange['data']['terms_text']['value'], $exchange['data']['terms_text']['format']),
  );
  $form['accept'] = array(
    '#type' => 'checkbox',
    '#title' => t('I\'ve read and accept the terms for being a member of :exchange.', array(':exchange' => $exchange['name'])),
    '#default_value' => isset($form_state['values']['accept']) ? $form_state['values']['accept'] : FALSE,
  );
  $form['actions'] = array();
  $form['actions']['next'] = array(
    '#type' => 'submit',
    '#value' => t('Next >>'),
    '#submit' => array('ces_user_register_save_values', 'ces_user_terms_form_submit')
  );
  $form['#validate'][] = 'ces_user_terms_form_validate';
  return $form;
}
function ces_user_terms_form_validate($form, &$form_state) {
  if (empty($form_state['values']['accept'])) {
    form_set_error('accept', t('You must accept the terms.'));
  }
}
function ces_user_register_form_previous($form, &$form_state) {
  if (isset($form_state['page_values']['terms'])) {
    $form_state['values'] = $form_state['page_values']['terms'];
  }
  $form_state['page'] = 'terms';
  $form_state['rebuild'] = TRUE;
}
function ces_user_terms_form_submit($form, &$form_state) {
  // Restore saved values.
  if (isset($form_state['page_values']['account'])) {
    $form_state['values'] = $form_state['page_values']['account'];
  }
  $form_state['page'] = 'account';
  $form_state['rebuild'] = TRUE;
}

/**
 * Save values in user register form account page.
 */
function ces_user_register_save_values($form, &$form_state) {
  $page = _ces_user_register_form_page($form_state);
  if ($page == 'terms' || $page == 'account') {
    $form_state['page_values'][$page] = $form_state['values'];
  }
}
/**
 * Submit user register form.
 */
function ces_user_register_submit($form, &$form_state) {
  module_load_include('module', 'user');
  $form_state['values'] = $form_state['page_values']['account'];
  $form = user_register_form($form, $form_state);
  user_register_submit($form, $form_state);
  $form_state['redirect'] = 'ces/user/registered/' . $form_state['page_values']['bankaccount']['exchange'];
}
/**
 * Implements hook_form_alter().
 *
 * Applies to ces_user_register_form & user_profile_form forms.
 */
function ces_user_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'ces_user_register_form' || $form_id == 'user_profile_form') {
    if ($form_id == 'user_profile_form' || _ces_user_register_form_page($form_state) == 'account') {
      // Move all ces fields to account fieldset.
      foreach ($form as $key => $field) {
        if (strlen($key) > 4 && substr($key, 0, 4) == 'ces_') {
          _ces_user_translate_field($field);
          $form['account'][$key] = $field;
          unset($form[$key]);
        }
      }
      $form['account']['picture'] = $form['picture'];
      unset($form['picture']);
      // Put default values in form elements (Drupal doesn't make it because we
      // are registering).
      if (isset($form_state['values'])) {
        _ces_user_set_form_values($form['account'], $form_state['values']);
      }
      // Set up weights.
      $form['account']['name']['#weight'] = -10;
      $form['account']['current_pass']['#weight'] = -5;
      $form['account']['pass']['#weight'] = 0;
      $form['account']['status']['#weight'] = 60;
      $form['account']['roles']['#weight'] = 65;
    }
  }
  elseif ($form_id == 'user_login_block') {
    // Override $form['links'].
    $items = array();
    $items[] = l(t('Forgot password?'), 'user/password', array('attributes' => array('title' => t('Request new password via e-mail.'))));
    $form['actions']['#weight'] = 90;
    $form['links'] = array(
      '#markup' => theme('item_list', array('items' => $items)),
      '#weight' => 100,
    );
    $form['end'] = array(
      '#markup' => '<div class="clearfix"></div>',
      '#weight' => 200,
    );
  }
  else if ($form_id == 'ces_bank_exchange_form') {
    module_load_include('module', 'ces_bank');
    $exchange = ces_bank_get_current_exchange();
    $form['exchange']['terms'] = array(
      '#type' => 'fieldset',
      '#title' => t('Terms'),
      '#description' => t('Membership terms of use'),
    );
    $form['exchange']['terms']['require_terms'] = array(
      '#type' => 'checkbox',
      '#title' => t('Require terms agreement'),
      '#default_value' => isset($form_state['values']['data']['require_terms']) ? $form_state['values']['data']['require_terms'] : FALSE,
    );

    if (isset($form_state['values']['data']['terms_text'])) {
      $text = $form_state['values']['data']['terms_text']['value'];
      $format = $form_state['values']['data']['terms_text']['format'];
    }
    $form['exchange']['terms']['terms_text'] = array(
      '#type' => 'text_format',
      '#title' => t('Terms text'),
      '#default_value' => isset($text) ? $text : '',
      '#format' => isset($format) ? $format : NULL,
    );
    $form['#validate'][] = 'ces_user_exchange_form_validate';
  }
}
function ces_user_exchange_form_validate($form, &$form_state) {
  if (!isset($form_state['values']['data'])) {
    $form_state['values']['data'] = array();
  }
  $form_state['values']['data']['require_terms'] = $form_state['values']['require_terms'];
  $form_state['values']['data']['terms_text'] = $form_state['values']['terms_text'];
}
/**
 * Helper function. Translates label and description of attached fields.
 */
function _ces_user_translate_field(&$field) {
  // This function is a hack to translate the label and description of attached
  // fields to the user entity by this module. The "best practice" way to do it
  // would be to use the i18n_field module, but I think it isn't worth to depend
  // on i18n just to translate labels and descriptions of programmatically added
  // fields.
  if (isset($field['#title'])) {
    // Yes, I know that only string literals should be passed to t()...
    $field['#title'] = t('@title', array('@title' => $field['#title']));
  }
  if (isset($field['#description'])) {
    $field['#description'] = t('@description', array('@description' => $field['#description']));
  }
  $children = element_children($field);
  if (is_array($children)) {
    foreach ($children as $child) {
      _ces_user_translate_field($field[$child]);
    }
  }
}
/**
 * Helper function. Sets default values to form elements.
 */
function _ces_user_set_form_values(&$elements, $values) {
  foreach ($values as $key => $value) {
    if (isset($elements[$key]) && is_array($elements[$key])) {
      if (is_array($value)) {
        // Call recursively.
        _ces_user_set_form_values($elements[$key], $value);
      }
      else {
        $elements[$key]['#default_value'] = $value;
      }
    }
  }
}
/**
 * User view.
 */
function ces_user_user_view($account, $view_mode, $langcode) {
  // Set fields to be rendered with user profile item theme.
  $account->content['account'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'class' => array(
        'user-profile-account-items',
      ),
    ),
  );
  foreach ($account->content as $key => $item) {
    if (substr($key, 0, 4) == 'ces_') {
      $item['#theme'] = 'user_profile_item';
      if (isset($item[0])) {
        $item['#markup'] = $item[0]['#markup'];
      }
      _ces_user_translate_field($item);
      $account->content['account'][$key] = $item;
      unset($account->content[$key]);
    }
  }
  $account->content['account']['ces_fullname'] = array(
    '#type' => 'markup',
    '#prefix' => '<h3 class="user-profile-ces-fullname">',
    '#suffix' => '</h3>',
    '#markup' => ces_user_get_name($account),
    'weight' => 0,
  );
  $account->content['account']['ces_fulladdress'] = array(
    '#theme' => 'user_profile_item',
    '#title' => t('Address'),
    '#markup' => ces_user_get_full_address($account),
    '#weight' => 15,
  );
  $account->content['account']['ces_email'] = array(
    '#theme' => 'user_profile_item',
    '#title' => t('Email'),
    '#markup' => $account->mail,
    '#weight' => 25,
  );
}
/**
 * Implements hook_block_info().
 */
function ces_user_block_info() {
  $block = array(
    'ces_user_register' => array(
      'info' => t('CES register'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
    ),
    'ces_user_links' => array(
      'info' => t('CES front links'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
    ),
  );
  return $block;
}
/**
 * Implements hook_block_view().
 */
function ces_user_block_view($delta = '') {
  global $user;
  $block = array();
  $block['subject'] = '';
  $content = array();
  if ($delta == 'ces_user_register') {
    if (!$user->uid) {
      $content = drupal_get_form('ces_user_register_block_form');
    }
  }
  elseif ($delta == 'ces_user_links') {
    if (!$user->uid) {
      $items = array();
      _ces_user_add_user_link($items, t('New exchange'), variable_get(CES_USER_NEW_EXCHANGE_URL, CES_USER_NEW_EXCHANGE_URL_DEF));
      _ces_user_add_user_link($items, t('Documentation'), variable_get(CES_USER_DOCUMENTATION_URL, CES_USER_DOCUMENTATION_URL_DEF));
      _ces_user_add_user_link($items, t('Developers'), variable_get(CES_USER_DEVELOPERS_URL, CES_USER_DEVELOPERS_URL_DEF));
      _ces_user_add_user_link($items, t('Donate'), variable_get(CES_USER_DONATE_URL, CES_USER_DONATE_URL_DEF));
      _ces_user_add_user_link($items, t('Terms of service'), variable_get(CES_USER_TERMS_OF_SERVICE_URL, CES_USER_TERMS_OF_SERVICE_URL_DEF));
      _ces_user_add_user_link($items, t('About'), variable_get(CES_USER_ABOUT_URL, CES_USER_ABOUT_URL_DEF));
      $content = array(
        '#theme' => 'item_list',
        '#attributes' => array('class' => array('front-links')),
        '#items' => $items,
      );
    }
  }
  $block['content'] = $content;
  return $block;
}
/**
 * Helper.
 */
function _ces_user_add_user_link(&$items, $text, $url) {
  if ($url) {
    global $language;
    $url = format_string($url, array('@langcode' => $language->language));
    $url = drupal_parse_url($url);
    $items[] = l($text, $url['path'], $url);
  }
}
/**
 * Form for choosing country on registering.
 */
function ces_user_register_block_form($form, &$form_state) {
  module_load_include('module', 'ces_bank');
  $options = ces_bank_country_get_list();
  array_unshift($options, t('Select country...'));
  $form = array(
    'text' => array(
      '#type' => 'container',
      'p1' => array(
        '#markup' => t('New to IntegralCES?'),
        '#prefix' => '<p><strong>',
        '#suffix' => '</strong></p>',
      ),
      'p2' => array(
        '#markup' => t('Find an exchange near you and start using social money:'),
      ),
      'country' => array(
        '#type' => 'select',
        '#options' => $options,
        '#attributes' => array('onChange' => array('this.form.submit()')),
      ),
      'submit' => array(
        '#type' => 'submit',
        '#value' => t('Register'),
        '#attributes' => array('style' => array('display: none;')),
      ),
      '#attributes' => array(),
    ),
  );
  return $form;
}
/**
 * Submit function.
 */
function ces_user_register_block_form_submit($form, &$form_state) {
  drupal_goto('ces/bank/exchange/list/' . $form_state['values']['country']);
}
/**
 * Menu callback.
 */
function ces_user_main_page() {
  global $user;
  if ($user->uid) {
    drupal_goto('ces/bank/exchange/blog');
  }
  return array(
    'welcome' => array(
      '#prefix' => '<p class="front-welcome">',
      '#suffix' => '</p>',
      '#markup' => t('Welcome to <strong>Integral Community Exchange System</strong>,'),
    ),
    'intro' => array(
      '#prefix' => '<p class="front-intro">',
      '#suffix' => '</p>',
      '#markup' => t('an open source platform featuring social currencies management for communities.'),
    ),
    'features' => array(
      '#theme' => 'item_list',
      '#items' => array(
        'local' => t('Boost local economy, return it to human scale.'),
        'eco' => t('Help the environment, lower contamination.'),
        'speculation' => t('Gain the control over money, prevent speculation and abuse.'),
        'alternative' => t('Create a solid alternative to the current financial system.'),
        'community' => t('Empower your community. Have fun playing with social currency.'),
      ),
      '#attributes' => array('class' => array('front-list')),
    ),
  );
}
/**
 * Implements hook_token_info().
 */
function ces_user_token_info() {
  return array(
    'tokens' => array(
      'user' => array(
        'fullname' => array(
          'name' => t('Full user name'),
          'description' => t('The full real user name'),
        ),
        'mainphone' => array(
          'name' => t('Main user telephone'),
          'description' => t('The main user telephone'),
        ),
      ),
    ),
  );
}
/**
 * Implements hook_tokens().
 */
function ces_user_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();
  $sanitize = !empty($options['sanitize']);
  if ($type == 'user' && !empty($data['user'])) {
    $user = $data['user'];
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'fullname':
          $fullname = ces_bank_get_full_username($user);
          $replacements[$original] = $sanitize ? check_plain($fullname) : $fullname;
          break;

        case 'mainphone':
          $mainphone = ces_user_get_main_phone($user);
          $replacements[$original] = $sanitize ? check_plain($mainphone) : $mainphone;
          break;
      }
    }
  }
  return $replacements;
}
/**
 * End of registration page callback.
 */
function ces_user_registered($exchange_id) {
  $exchange = ces_bank_get_exchange($exchange_id);
  $admin = user_load($exchange['admin']);
  return array(
    'success' => array(
      '#prefix' => '<p>',
      '#suffix' => '</p>',
      '#markup' => t('You have successfully registered to the exchange %name in the Integral Community Exchange System.',
        array('%name' => $exchange['name'])),
    ),
    'message' => array(
      '#prefix' => '<p>',
      '#suffix' => '</p>',
      '#markup' => t('Before you can start using the system, the administration of your exchange must authorize your account. You will receive an email when your account is activated with further instructions. If you have no news in these comming days, contact your exchange administration at %mail.',
        array('%mail' => $admin->mail)),
    ),
    'message2' => array(
      '#prefix' => '<p>',
      '#suffix' => '</p>',
      '#markup' => t('See you soon!'),
    ),
  );
}

/**
 * Implements hook_admin().
 */
function ces_user_admin() {
  $form = array();
  $form[CES_USER_NEW_EXCHANGE_URL] = array(
    '#type' => 'textfield',
    '#title' => t('New exchange URL'),
    '#default_value' => variable_get(CES_USER_NEW_EXCHANGE_URL, CES_USER_NEW_EXCHANGE_URL_DEF),
    '#description' => t('The URL of the new exchange form or intermediate custom page. You can use the placeholder @langcode for the current language ISO code. If you let it empty the link will be hidden.'),
  );
  $form[CES_USER_DOCUMENTATION_URL] = array(
    '#type' => 'textfield',
    '#title' => t('Documentation URL'),
    '#default_value' => variable_get(CES_USER_DOCUMENTATION_URL, CES_USER_DOCUMENTATION_URL_DEF),
    '#description' => t('The url of the general documentation page.'),
  );
  $form[CES_USER_DEVELOPERS_URL] = array(
    '#type' => 'textfield',
    '#title' => t('Developers URL'),
    '#default_value' => variable_get(CES_USER_DEVELOPERS_URL, CES_USER_DEVELOPERS_URL_DEF),
    '#description' => t('The url of the IntegralCES develop site.'),
  );
  $form[CES_USER_DONATE_URL] = array(
    '#type' => 'textfield',
    '#title' => t('Donate URL'),
    '#default_value' => variable_get(CES_USER_DONATE_URL, CES_USER_DONATE_URL_DEF),
    '#description' => t('The url of the donations page.'),
  );
  $form[CES_USER_TERMS_OF_SERVICE_URL] = array(
    '#type' => 'textfield',
    '#title' => t('Terms of service URL'),
    '#default_value' => variable_get(CES_USER_TERMS_OF_SERVICE_URL, CES_USER_TERMS_OF_SERVICE_URL_DEF),
    '#description' => t('The terms of service page.'),
  );
  $form[CES_USER_ABOUT_URL] = array(
    '#type' => 'textfield',
    '#title' => t('About URL'),
    '#default_value' => variable_get(CES_USER_ABOUT_URL, CES_USER_ABOUT_URL_DEF),
    '#description' => t('The about page.'),
  );
  $form[CES_USER_GOOGLE_MAPS_KEY] = array(
    '#type' => 'textfield',
    '#title' => t('Google Maps API Key'),
    '#default_value' => variable_get(CES_USER_GOOGLE_MAPS_KEY, $ces_user_google_maps_key_def),
    '#description' => t('Google Maps API Key.'),
  );
  return system_settings_form($form);
}
/**
 * Geocode empty location fields
 */
function ces_user_field_attach_presave($entity_type, $entity) {
  if ($entity_type == 'user') {
    $items = field_get_items('user', $entity, 'ces_geolocation');
    $empty = TRUE;
    if (!empty($items)) {
      $item = reset($items);
      $empty = empty($item['lat']) && empty($item['lng']);
    }
    if ($empty) {
      $text = ces_user_get_full_address($entity);
      if (!empty(trim($text, ' ,'))) {
        watchdog('ces_user', 'Calling google maps API for user %name', ['%name' => $entity->name]);
        $geocode = ces_user_geocode($text);
        $field_value = _ces_user_geolocation_field_value($geocode);
        if ($field_value) {
          $entity->ces_geolocation = array(
            LANGUAGE_NONE => [$field_value]
          );
        }
      }
    }
  }
}
function _ces_user_cid($text) {
  return 'ces_geo:' . sha1($text);
}
function ces_user_geocode_cache_get($text) {
  $cid = _ces_user_cid($text);
  if ($cache = cache_get($cid)) {
    return $cache->data;
  }
  return false;
}
function ces_user_geocode_cache_set($text, $data) {
  $cid = _ces_user_cid($text);
  cache_set($cid, $data);
}

function ces_user_geocode($text) {
  $result = ces_user_geocode_cache_get($text);
  if (!$result) {
    $result = ces_user_geocode_call($text);
    ces_user_geocode_cache_set($text, $result);
  }
  return $result;
}
function ces_user_geocode_call($text) {

  $ces_user_google_maps_key_def = getenv('CES_USER_GOOGLE_MAPS_KEY');
  $ces_user_google_maps_key_def = !empty($ces_user_google_maps_key_def) ? $ces_user_google_maps_key_def : '';

  $maps_url = 'https://maps.googleapis.com/maps/api/geocode/json';
  $key = variable_get(CES_USER_GOOGLE_MAPS_KEY, $ces_user_google_maps_key_def);
  if (empty($key)) {
    watchdog('ces_user', 'Missing Google Maps API Key.', null, WATCHDOG_ERROR);
    return false;
  }
  $url = url($maps_url, ['query' => [
    'address' => $text,
    'key' => $key
  ]]);
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_URL, $url);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
  curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5);
  curl_setopt($ch, CURLOPT_HEADER, 0);
  $data = curl_exec($ch);
  curl_close($ch);
  if ($data) {
    $data = json_decode($data);
    if ($data->status == 'OK') {
      // Get the first result
      $item = reset($data->results);
      $lng = $item->geometry->location->lng;
      $lat = $item->geometry->location->lat;
      return array(
        'lat' => $lat,
        'lng' => $lng,
      );
    }
  }
  return false;
}
function _ces_user_geolocation_field_value($geocode) {
  $lat = $geocode && isset($geocode['lat']) ? $geocode['lat'] : 0;
  $lng = $geocode && isset($geocode['lng']) ? $geocode['lng'] : 0;
  return array(
    'lat' => $lat,
    'lng' => $lng,
    'lat_sin' => sin(deg2rad($lat)),
    'lat_cos' => cos(deg2rad($lat)),
    'lng_rad' => deg2rad($lng),
  );
}

define('_CES_USER_DEFAULT_NOTIFICATION_SETTINGS', 'anom'); // all notifications
define('_CES_USER_DEFAULT_EMAILS_SETTINGS', 'am'); // account emails + monthly newsletter.
/**
 * return the array of user settings:
 * [
 * 'language' => string, // the language code
 * 'komunitin' => bool,  // if true, the user is using the komunitin interface
 * 'notifications' => [
 *   'myAccount' => bool,  // if true, the user wants to receive notifications about his account
 *   'newNeeds' => bool,  // if true, the user wants to receive notifications about new needs
 *   'newOffers' => bool,  // if true, the user wants to receive notifications about new offers
 *   'newMembers' => bool,  // if true, the user wants to receive notifications about new members
 * ],
 * 'emails' => [
 *   'myAccount' => bool,  // if true, the user wants to receive emails about his account
 *   'group' => "never" | "daily" | "weekly" | "monthly" | "quarterly",  // the frequency of group emails
 *  ]
 * ]
 */
function ces_user_get_settings($user) {
  $settings = array();
  // Get language from drupal core.
  $lang = user_preferred_language($user);
  $settings['language'] = $lang->language;

  // Get notifications settings from user->data. We use a rudimentary compressed
  // encoding to save space in the data field.
  $user_settings = isset($user->data['ces_user_settings']) ? $user->data['ces_user_settings'] : array();
  // notifications
  $nstr = isset($user_settings['n']) ? $user_settings['n'] : _CES_USER_DEFAULT_NOTIFICATION_SETTINGS;
  $settings['notifications'] = array(
    'myAccount' => strpos($nstr, 'a') !== FALSE,
    'newNeeds' => strpos($nstr, 'n') !== FALSE,
    'newOffers' => strpos($nstr, 'o') !== FALSE,
    'newMembers' => strpos($nstr, 'm') !== FALSE,
  );
  // komunitin
  $kstr = isset($user_settings['k']) ? $user_settings['k'] : '';
  $settings['komunitin'] = strpos($kstr, '1') !== FALSE;
  // emails
  $estr = isset($user_settings['e']) ? $user_settings['e'] : _CES_USER_DEFAULT_EMAILS_SETTINGS;
  $group = 'never';
  if (strpos($estr, 'd') !== FALSE) {
    $group = 'daily';
  }
  else if (strpos($estr, 'w') !== FALSE) {
    $group = 'weekly';
  }
  else if (strpos($estr, 'm') !== FALSE) {
    $group = 'monthly';
  }
  else if (strpos($estr, 'q') !== FALSE) {
    $group = 'quarterly';
  }

  $settings['emails'] = array(
    'myAccount' => strpos($estr, 'a') !== FALSE,
    'group' => $group,
  );

  return $settings;
}

/**
 * @param $data: the user data array
 * @return $edit the user edit array with the settings encoded in the
 * ['language'] key and in the ['data']['ces_user_settings'] key.
 */
function ces_user_build_settings_data($data, $settings) {
  $edit = array();
  // Set language in drupal core.
  if (isset($settings['language'])) {
    $lang = $settings['language'];
    $edit['language'] = $lang;
  }
  // Set notifications settings in user->data. We use a compressed encoding to
  // save space in the data field.

  $edit['data'] = $data;
  if (!isset($edit['data']['ces_user_settings'])) {
    $edit['data']['ces_user_settings'] = array();
  }

  if (isset($settings['notifications'])) {
    $nstr = '';
    $notifications = $settings['notifications'];
    if ($notifications['myAccount']) {
      $nstr .= 'a';
    }
    if ($notifications['newNeeds']) {
      $nstr .= 'n';
    }
    if ($notifications['newOffers']) {
      $nstr .= 'o';
    }
    if ($notifications['newMembers']) {
      $nstr .= 'm';
    }
    $edit['data']['ces_user_settings']['n'] = $nstr;
  }

  if (isset($settings['komunitin'])) {
    $edit['data']['ces_user_settings']['k'] = $settings['komunitin'] ? '1' : '';
  }

  if (isset($settings['emails'])) {
    $estr = '';
    $emails = $settings['emails'];
    if ($emails['myAccount']) {
      $estr .= 'a';
    }
    if ($emails['group'] == 'daily') {
      $estr .= 'd';
    }
    else if ($emails['group'] == 'weekly') {
      $estr .= 'w';
    }
    else if ($emails['group'] == 'monthly') {
      $estr .= 'm';
    }
    else if ($emails['group'] == 'quarterly') {
      $estr .= 'q';
    }
    $edit['data']['ces_user_settings']['e'] = $estr;
  }

  return $edit;
}

function ces_user_set_settings(&$user, $settings) {
  $edit = ces_user_build_settings_data($user->data, $settings);
  $user = user_save($user, $edit);
}

function ces_user_get_contacts($user) {
  $contacts = array();
  // Always email contact.
  $contacts['email'] = $user->mail;
  // Phone contact.
  $phone = ces_user_get_main_phone($user);
  if (!empty($phone)) {
    $contacts['phone'] = $phone;
  }
  // Website contact.
  if (!empty($user->ces_website) && !empty($user->ces_website[LANGUAGE_NONE][0]['value'])) {
    $contacts['website'] = $user->ces_website[LANGUAGE_NONE][0]['value'];
  }
  // Additional contacts.
  if (isset($user->data['ces_user_contacts'])) {
    $data = $user->data['ces_user_contacts'];
    foreach ($data as $key => $value) {
      $contacts[$key] = $value;
    }
  }
  return $contacts;
}

function ces_user_set_contacts(&$user, $contacts) {
  $edit = array();
  // Do NOT edit email this way.
  unset($contacts['email']);
  // Save phone in special field.
  $edit['ces_phonemobile'] = [
    LANGUAGE_NONE => [['value' => !empty($contacts['phone']) ? $contacts['phone'] : NULL]]
  ];
  unset($contacts['phone']);
  // Save website in special field.
  $edit['ces_website'] = [
    LANGUAGE_NONE => [['value' => !empty($contacts['website']) ? $contacts['website'] : NULL]]
  ];
  // Save other contacts in $user->data.
  $edit['data'] = $user->data;
  $edit['data']['ces_user_contacts'] = $contacts;

  $user = user_save($user, $edit);
}

/**
 * @}
 */
