version: "3.5"
services:
  db: 
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: integralces
      MYSQL_USER: integralces
      MYSQL_PASSWORD: ${ICES_MYSQL_PASSWORD:-integralces}
    volumes:
      - db:/var/lib/mysql
    networks:
      - komunitin
  
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports: 
      - 2026:80
    environment:
      PMA_HOST: db
    networks:
      - komunitin

  integralces:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    ports: 
      - 2029:2029
    volumes:
      - .:/var/www/html/sites/all/modules/ices
      - files:/var/www/html/sites/default
      
    environment:
      - NOTIFICATIONS_CLIENT_ID=${NOTIFICATIONS_CLIENT_ID:-notifications-service}
      - NOTIFICATIONS_CLIENT_SECRET=${NOTIFICATIONS_CLIENT_SECRET:-komunitin}
      - NOTIFICATIONS_API_URL=${NOTIFICATIONS_API_URL:-http://notifications:2028}
      - NOTIFICATIONS_EVENTS_USERNAME=${NOTIFICATIONS_EVENTS_USERNAME:-integralces}
      - NOTIFICATIONS_EVENTS_PASSWORD=${NOTIFICATIONS_EVENTS_PASSWORD:-komunitin}
      - MAILERSEND_API_KEY=${MAILERSEND_API_KEY:-'mlsn.xxxxxxxxxxxxxx'}
    networks:
      - komunitin

networks:
  komunitin:
    name: komunitin

volumes:
  db:
  files:
