version: "3.3"
services:
  integralces:
    build: .
    ports: 
      - 2029:2029
    volumes:
      - type: bind
        source: .
        target: /var/www/html/sites/all/modules/ices
    environment:
      - NOTIFICATIONS_CLIENT_ID=notifications-service
      - NOTIFICATIONS_CLIENT_SECRET=komunitin
      - NOTIFICATIONS_API_URL=http://notifications:2028
    networks:
      - komunitin
networks:
  komunitin:
    driver: bridge
    name: komunitin

