<?php
/**
 * @file
 * Installation for ces_rest module.
 */

/**
 * Implements hook_install().
 *
 * Oauth2 authorisation codes and tokens.
 */
function ces_rest_install() {
  // Create Oauth2 server for ICES REST services.
  $server = entity_create('oauth2_server', array());
  $server->name = 'cesrest';
  $server->label = 'ICES REST SERVICE';
  $server->settings = array(
    'default_scope' => 'cesrest',
    'enforce_state' => TRUE,
    'allow_implicit' => FALSE,
    'require_exact_redirect_uri' => TRUE,
    'grant_types' => array(
      'authorization_code' => 'authorization_code',
      'client_credentials' => 0,
      'refresh_token' => 'refresh_token',
      'password' => 0,
    ),
    'always_issue_new_refresh_token' => FALSE,
    'access_lifetime' => 3600,
    'refresh_token_lifetime' => 1209600,
  );
  $server->save();

  // Create OAuth2 scope for resurces API.
  $scope = entity_create('oauth2_server_scope', array());
  $scope->server = $server->name;
  $scope->name = 'cesrest';
  $scope->description = 'Ces Rest';
  $scope->save();

  // Import service.
  $endpoint = new stdClass();
  $endpoint->disabled = FALSE; /* Edit this to true to make a default endpoint disabled initially */
  $endpoint->api_version = 3;
  $endpoint->name = 'cesrest';
  $endpoint->server = 'rest_server';
  $endpoint->path = 'cesrest';
  $endpoint->authentication = array(
    'oauth2_server' => array(
      'server' => 'cesrest',
    ),
  );
  $endpoint->server_settings = array(
    'formatters' => array(
      'json' => TRUE,
      'bencode' => FALSE,
      'jsonp' => FALSE,
      'php' => FALSE,
      'xml' => FALSE,
    ),
    'parsers' => array(
      'application/json' => TRUE,
      'application/x-www-form-urlencoded' => TRUE,
      'application/vnd.php.serialized' => FALSE,
      'application/xml' => FALSE,
      'multipart/form-data' => FALSE,
      'text/xml' => FALSE,
    ),
  );
  $endpoint->resources = array(
    // Users.
    'cr_users' => array(
      'alias' => 'users',
      'actions' => array(
        'create' => array(
          'enabled' => '1',
          'settings' => array(
            'oauth2_server' => array(
              'require_authentication' => '1',
              'scope' => 'cesrest',
            ),
          ),
        ),
        'update' => array(
          'enabled' => '1',
          'settings' => array(
            'oauth2_server' => array(
              'require_authentication' => '1',
              'scope' => 'cesrest',
            ),
          ),
        ),
      ),
      'operations' => array(
        'index' => array(
          'enabled' => '1',
          'settings' => array(
            'oauth2_server' => array(
              'require_authentication' => '1',
              'scope' => 'cesrest',
            ),
          ),
        ),
      ),
    ),
    // Accounts.
    'cr_accounts' => array(
      'alias' => 'accounts',
      'actions' => array(
        'create' => array(
          'enabled' => '1',
          'settings' => array(
            'oauth2_server' => array(
              'require_authentication' => '1',
              'scope' => 'cesrest',
            ),
          ),
        ),
        'update' => array(
          'enabled' => '1',
          'settings' => array(
            'oauth2_server' => array(
              'require_authentication' => '1',
              'scope' => 'cesrest',
            ),
          ),
        ),
      ),
      'operations' => array(
        'index' => array(
          'enabled' => '1',
          'settings' => array(
            'oauth2_server' => array(
              'require_authentication' => '1',
              'scope' => 'cesrest',
            ),
          ),
        ),
      ),
    ),
    // Transactions.
    'cr_transactions' => array(
      'alias' => 'transactions',
      'operations' => array(
        'index' => array(
          'enabled' => '1',
          'settings' => array(
            'oauth2_server' => array(
              'require_authentication' => '1',
              'scope' => 'cesrest',
            ),
          ),
        ),
      ),
    ),
    // Exchange.
    'cr_exchange' => array(
      'alias' => 'exchange',
      'operations' => array(
        'index' => array(
          'enabled' => '1',
          'settings' => array(
            'oauth2_server' => array(
              'require_authentication' => '1',
              'scope' => 'cesrest',
            ),
          ),
        ),
      ),
    ),
  );
  $endpoint->debug = 1;

  // End export code.
  $endpoint->export_type = EXPORT_IN_CODE;
  services_endpoint_save($endpoint);
}

/**
 * Implements hook_uninstall().
 */
function ces_rest_uninstall() {
  $scope = oauth2_server_scope_load('cesrest', 'cesrest');
  if ($scope) {
    entity_delete('oauth2_server_scope', $scope->identifier());
  }
  $server = oauth2_server_load('cesrest');
  if ($server) {
    entity_delete('oauth2_server', $server->identifier());
  }
  // Delete services endpoint.
  $endpoint = services_endpoint_load('cesrest');
  if ($endpoint) {
    services_endpoint_delete($endpoint);
  }
}
