<?php
/**
 * @file
 * Drupal hooks for the ICES komunitin module.
 */

/**
 * @defgroup ces_komunitin_module ICES komunitin module
 * @ingroup ces_komunitin
 * @{
 * ICES komunitin module.
 */

 /**
  * Implements hook_module_implements_alter
  *
  * Ensures this is the last init hook call.
  */
function ces_komunitin_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'init') {
    $impl = $implementations['ces_komunitin'];
    unset($implementations['ces_komunitin']);
    $implementations['ces_komunitin'] = $impl;
  }
}
/**
 * Implements hook_init().
 *
 * Exit on OPTIONS requests so we dont check for Authorization.
 */
function ces_komunitin_init() {
  if ($_SERVER['REQUEST_METHOD'] == "OPTIONS") {
    exit(0);
  }
}
/**
 * Implements hook_menu.
 */
function ces_komunitin_menu() {
  $items = array();
  $items['ces/api'] = array(
    'page callback' => 'ces_komunitin_api',
    'type' => MENU_CALLBACK,
    'file' => 'ces_komunitin.api.inc',
    'file path' => drupal_get_path('module', 'ces_komunitin'),
    'access callback' => TRUE
  );
  return $items;
}
/**
 * Implements hook_libraries_info().
 */
function ces_komunitin_libraries_info()
{
  $libraries = array();
  $libraries['json-api'] = array(
    'name' => 'JSON API',
    'vendor url' => 'https://github.com/neomerx/json-api',
    'xautoload' => function ($adapter) {
      /** @var \Drupal\xautoload\Adapter\LocalDirectoryAdapter $adapter */
      // Scan sites/all/libraries/json-api/composer.json to look for
      // autoload information.
      $adapter->composerJson('composer.json');
    },
  );
  $libraries['html-to-markdown'] = array(
    'name' => 'HTML To Markdown for PHP',
    'vendor url' => 'https://github.com/thephpleague/html-to-markdown',
    'xautoload' => function ($adapter) {
      $adapter->composerJson('composer.json');
    }
  );
  return $libraries;
}

/**
 * Implements hook_notification invoked by function ces_message_send_notify at
 * ces_message/ces_message.module.
 */
function ces_komunitin_notification($action, $exchange_id, $user_recipient_id, $params, $sender_id = false) {
  module_load_include('inc', 'ces_komunitin', 'ces_komunitin.notifications');
  ces_komunitin_notification_event($action, $exchange_id, $user_recipient_id, $params, $sender_id);
}
