<?php
/**
 * @file
 * Install and uninstall ces offerswants module.
 */

/**
 * @defgroup ces_offerswants_install Install OffersWants
 * @ingroup ces_offerswants
 * @{
 * Install and uninstall ces offerswants module.
 */

/**
 * Implements hook_schema().
 */
function ces_offerswants_schema() {
  $schema = array();
  $schema['ces_offerwant'] = array(
    'description' => 'Main table for offers and wants entities.',
    'fields' => array(
      'id' => array(
        'description' => 'ID of this offer or want',
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'type' => array(
        'description' => 'The type of this entity. It is one of: offer, want.',
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
        'default' => '',
      ),
      'user' => array(
        'description' => 'UID of the owner user',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'title' => array(
        'description' => 'The title of this offer or want, always treated as non-markup plain text.',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'body' => array(
        'description' => 'The body of this offer or want. It is HTML.',
        'type' => 'text',
        'size' => 'big',
        'not null' => TRUE,
      ),
      'image' => array(
        'description' => 'Image source for this offer or want.',
        'type' => 'varchar',
        'length' => 255,
      ),
      'category' => array(
        'description' => 'Reference to category table.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'keywords' => array(
        'description' => 'Keywords for this offer or want',
        'type' => 'text',
        'size' => 'big',
        'not null' => TRUE,
      ),
      'state' => array(
        'description' => 'The state of this offer. 0 = hidden, 1 = public',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'created' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'modified' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'expire' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'code' => array(
        // The komunitin offer/need code or slug.
        'type' => 'varchar',
        'length' => 200,
        'not null' => TRUE,
      )
    ),
    'primary key' => array('id'),
    'unique keys' => array(
      'code' => array('code'),
    ),
  );
  $schema['ces_category'] = array(
    'description' => 'Table for offers and wants categories.',
    'fields' => array(
      'id' => array(
        'description' => 'ID of this offer or want',
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'parent' => array(
        'description' => 'Parent category',
        'type' => 'int',
        'unsigned' => TRUE,
        'default' => 0,
      ),
      'title' => array(
        'description' => 'Title for this category',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'description' => array(
        'description' => 'Detailed description of this category',
        'type' => 'text',
        'size' => 'big',
        'not null' => TRUE,
      ),
      'exchange' => array(
        'description' => 'The id of the exchange where this category belongs',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'context' => array(
        'description'   => 'Whether this category is applicable to offers (1), wants (2), both (3) or none (0)',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'code' => array(
        // The komunitin offer/need code or slug.
        'type' => 'varchar',
        'length' => 200,
        'not null' => TRUE,
      )
    ),
    'primary key' => array('id'),
    'foreign keys' => array(
      'parent' => array(
        'table' => 'ces_category',
        'columns' => array('parent' => 'id'),
      ),
    ),
    'unique keys' => array(
      'code' => array('code'),
    ),
  );
  $schema['ces_offercomment'] = array(
    'description' => 'Table for comments and ratings on offers.',
    'fields' => array(
      'cid' => array(
        'description' => 'Primary Key: Unique comment ID.',
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'oid' => array(
        'description' => 'The {ces_offerwant}.id of the parent offer.',
        'type' => 'int',
        'unsigned' => TRUE,
        'default' => 0,
      ),
      'uid' => array(
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'description' => 'The {users}.uid who authored the comment.',
      ),
      'body' => array(
        'description' => 'The body of this comment. It is HTML.',
        'type' => 'text',
        'size' => 'big',
        'not null' => TRUE,
      ),
      'rating' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'description' => 'Rating of the offer: from 0 to 5.',
      ),
      'created' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'The time that the comment was created, as a Unix timestamp.',
      ),
    ),
    'primary key' => array('cid'),
  );
  $schema['ces_alerts'] = array(
    'description' => 'Table for offers&wants alerts of each exchange.',
    'fields' => array(
      'id' => array(
        'description' => 'Primary Key: Unique alert ID.',
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'exchange' => array(
        'description' => 'The {ces_exchange}.id of the alerts.',
        'type' => 'int',
        'unsigned' => TRUE,
        'default' => 0,
      ),
      'expired_status' => array(
        'description' => 'Enabled/disabled alert offerwant expired.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 1,
      ),
      'expired_lasttime' => array(
        'description' => 'Last time cron runs alert offerwant expired, as a Unix timestamp.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'newoffer_status' => array(
        'description' => 'Enabled/disabled alert newoffer.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 1,
      ),
      'newoffer_lasttime' => array(
        'description' => 'Last time cron runs alert newoffer, as a Unix timestamp.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'newwant_status' => array(
        'description' => 'Enabled/disabled alert newwant.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 1,
      ),
      'newwant_lasttime' => array(
        'description' => 'Last time cron runs alert newwant, as a Unix timestamp.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'offersperiodical_status' => array(
        'description' => 'Alert offers periodical: disabled(0), weekly(1), biweekly(2), monthly(3), bimonthly(4).',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 1,
      ),
      'offersperiodical_lasttime' => array(
        'description' => 'Last time cron runs alert offers periodical, as a Unix timestamp.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'wantsperiodical_status' => array(
        'description' => 'Alert wants periodical: disabled(0), weekly(1), biweekly(2), monthly(3), bimonthly(4).',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 1,
      ),
      'wantsperiodical_lasttime' => array(
        'description' => 'Last time cron runs alert wants periodical, as a Unix timestamp.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'created' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'The time that the alerts for this exchange were created, as a Unix timestamp.',
      ),
    ),
    'primary key' => array('id'),
  );
  $schema['ces_user_alerts'] = array(
    'description' => 'Email subscription for each user to different events and newsletters.',
    'fields' => array(
      'user' => array(
        'description' => 'The drupal user uid',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'alert' => array(
        'description' => 'The ces_alert id',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'expired' => array(
        'description' => 'Boolean. Subscribed to own offer/want expire event.',
        'type' => 'int',
        'size' => 'tiny',
        'default' => 1,
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'newoffer' => array(
        'description' => 'Boolean. Subscribed to new offer event.',
        'type' => 'int',
        'size' => 'tiny',
        'default' => 1,
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'newwant' => array(
        'description' => 'Boolean. Subscribed to new want event.',
        'type' => 'int',
        'size' => 'tiny',
        'default' => 1,
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'offersperiodical' => array(
        'description' => 'Boolean. Subscribed to periodical last offers newsletter.',
        'type' => 'int',
        'size' => 'tiny',
        'default' => 1,
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'wantsperiodical' => array(
        'description' => 'Boolean. Subscribed to periodical last wants newsletter.',
        'type' => 'int',
        'size' => 'tiny',
        'default' => 1,
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
    ),
    'primary key' => array('user', 'alert'),
    'foreign keys' => array(
      'user' => array(
        'table' => 'user',
        'columns' => array('user' => 'uid'),
      ),
      'exchange' => array(
        'table' => 'ces_exchange',
        'columns' => array('exchange' => 'id'),
      ),
    ),
  );
  return $schema;
}

/**
 * Implements hook_update_N().
 */
function ces_offerswants_update_7100() {
  $schema = ces_offerswants_schema();
  db_create_table('ces_offercomment', $schema['ces_offercomment']);
}

/**
 * Implements hook_update_N().
 */
function ces_offerswants_update_7101() {
  $schema = ces_offerswants_schema();
  db_create_table('ces_alerts', $schema['ces_alerts']);
}
/**
 * Implements hook_update_N().
 */
function ces_offerswants_update_7102() {
  // We extend DefaultMailSystem class in ces_offerswants module,
  // for sending html emails.
  $current = variable_get('mail_system', array('default-system' => 'DefaultMailSystem'));
  $addition = array('ces_offerswants' => 'CesOfferswantsMailSystem');
  variable_set('mail_system', array_merge($current, $addition));
}
/**
 * Refactor alerts.
 */
function ces_offerswants_update_7103() {
  // Create user_alerts table
  $schema = ces_offerswants_schema();
  db_create_table('ces_user_alerts', $schema['ces_user_alerts']);
  // Populate new table.
  $alerts = db_select('ces_alerts', 'a')
    ->fields('a')
    ->execute()
    ->fetchAll();
  foreach($alerts as $alert) {
    // Get all exchange active user ids.
    $query = db_query("SELECT DISTINCT u.uid from {users} u
      LEFT JOIN {ces_accountuser} au ON u.uid = au.user
      LEFT JOIN {ces_account} a ON au.account = a.id
      WHERE a.exchange = :exchange
      AND u.status = 1",
      array(':exchange' => $alert->exchange));
    $users = $query->fetchCol();
    // Get the array of subscribed users for each alert.
    // The expired list is the complementary.
    $expired_noalertusers = explode(',', unserialize($alert->expired_noalertusers));
    $expired_users = array_diff($users, $expired_noalertusers);
    // Others are direct.
    $newoffer_users = explode(',', unserialize($alert->newoffer_onlyusers));
    $newwant_users = explode(',', unserialize($alert->newwant_onlyusers));
    $offersperiodical_users = explode(',', unserialize($alert->offersperiodical_onlyusers));
    $wantsperiodical_users = explode(',', unserialize($alert->wantsperiodical_onlyusers));

    // Create table record for each user:
    foreach($users as $user) {
      db_insert('ces_user_alerts')
        ->fields(array(
          'user' => $user,
          'alert' => $alert->id,
          'expired' => in_array($user, $expired_users) ? 1 : 0,
          'newoffer' => in_array($user, $newoffer_users) ? 1 : 0,
          'newwant' => in_array($user, $newwant_users) ? 1 : 0,
          'offersperiodical' => in_array($user, $offersperiodical_users) ? 1 : 0,
          'wantsperiodical' => in_array($user, $wantsperiodical_users) ? 1 : 0,
        ))
        ->execute();
    }
  }

  // Delete old table columns
  db_drop_field('ces_alerts', 'expired_noalertusers');
  db_drop_field('ces_alerts', 'newoffer_onlyusers');
  db_drop_field('ces_alerts', 'newwant_onlyusers');
  db_drop_field('ces_alerts', 'offersperiodical_onlyusers');
  db_drop_field('ces_alerts', 'wantsperiodical_onlyusers');
}

/**
 * Remove Mail System override.
 */
function ces_offerswants_update_7104() {
  $current = variable_get('mail_system', array('default-system' => 'DefaultMailSystem'));
  unset($current['ces_offerswants']);
  variable_set('mail_system', $current);
}

/**
 * Add code to offers and needs.
 */
function ces_offerswants_update_7105() {
  _ces_offerswants_add_code_field('ces_offerwant');
}

/**
 * Add code to categories.
 */
function ces_offerswants_update_7106() {
  _ces_offerswants_add_code_field('ces_category');
}

function _ces_offerswants_add_code_field($table) {
  // 1. Add new DB field code.
  if (!db_field_exists($table, 'code')) {
    $schema = ces_offerswants_schema();
    $spec = $schema[$table]['fields']['code'];
    $spec['initial'] = '';
    db_add_field($table, 'code', $spec);
  }
  // 2. Populate the field.
  $rows = db_select($table, 'o')
    ->fields('o', ['id', 'title'])
    ->execute();
  //in-memory hash of slugs just to check uniqueness
  $slugs = [];
  foreach ($rows as $row) {
    $slug = ces_offerswants_slugify($row->title);
    if (isset($slugs[$slug])) {
      $n = 2;
      while (isset($slugs[$slug . '-' . $n])) {
        $n++;
      }
      $slug = $slug . '-' . $n;
    }
    // got a unique slug: update db.
    $slugs[$slug] = TRUE;
    db_update($table)
      ->condition('id', $row->id)
      ->fields(['code' => $slug])
      ->execute();
  }
  // 3. Add index.
  $index_name = $table . '_unique_code';
  if (!db_index_exists($table, $index_name)) {
    db_add_unique_key($table, $index_name, array('code'));
  }
}

/**
 * Implements hook_install().
 */
function ces_offerswants_install() {
  $t = get_t();

  // Create price field.
  $field = array(
    'field_name' => 'ces_offer_rate',
    'type' => 'text',
    'cardinality' => 1,
  );
  $field = field_create_field($field);
  $instance = array(
    'field_name' => 'ces_offer_rate',
    'entity_type' => 'ces_offerwant',
    'bundle' => 'offer',
    'label' => 'Rate',
    'widget' => array(
      'type' => 'text_textfield',
      'weight' => 10,
    ),
    'display' => array(
      'default' => array('type' => 'ces_offer_rate'),
    ),
  );
  $instance = field_create_instance($instance);
}
/**
 * Implements hook_uninstall().
 */
function ces_offerswants_uninstall() {
  drupal_uninstall_schema(ces_offerswants_schema());

  // Special class for sending html emails no more needed.
  $mail_system = variable_get('mail_system', array('default-system' => 'DefaultMailSystem'));
  unset($mail_system['ces_offerswants']);
  variable_set('mail_system', $mail_system);

  // Delete price field.
  field_delete_field('ces_offer_rate');
  $instances = field_info_instances('ces_offerwant', 'ces_offer_rate');
  if (empty($instances)) {
    return;
  }

  foreach ($instances as $instance) {
    field_delete_instance($instance);
  }
  field_purge_batch(1000);
}
/** @} */
